### PR TITLE
[asset] add Savings CELO - sCELO

### PR DESCRIPTION
**Pull request by zviadm**

### CODE REVIEW

**Comment by zviadm** [comment]
i am guessing some instructions are missing in the README.
Does this require running `yarn build` so it autogenerates some files?

**Comment by macalinao** [comment]
> Does this require running `yarn build` so it autogenerates some files?

HI Zviad-- yes it does. Apologies

**Comment by zviadm** [comment]
> > Does this require running `yarn build` so it autogenerates some files?
> 
> HI Zviad-- yes it does. Apologies

You might also want to note that this requires at least Node v14. It doesn't work with earlier versions of Node.

**Comment by macalinao** [comment]
> You might also want to note that this requires at least Node v14. It doesn't work with earlier versions of Node.

Thanks for letting me know-- I'll do that. Longer term I'll probably just add some kind of GitHub Action to automatically run this script after a merge

**Pull request merged**
