### PR TITLE
Adding KARMAGE

### PR DESCRIPTION
**Pull request by dcxbutcher615**
Adding KARMAGE

### CODE REVIEW

**Comment by dcxbutcher615** [comment]
Any idea when this will get approved? ugh...

**Comment by dcxbutcher615** [comment]
Please hurry I got you linked on my webpage, I got people who want to utilize your app for swapping and supporting my coin.
please get my coin up! it's got value and hindering karmage. Thanks so much. DC ROBINSON  2 weeks I've waited.

**Comment by BriungRi** [comment]
Please add `experimental: true`

**Comment by dcxbutcher615** [comment]
to where?

**Comment by dcxbutcher615** [comment]
experimental: true

**Pull request closed without merging**
